apiVersion: v1
kind: Secret
metadata:
  name: keda-kafka-secrets
  namespace: keda-eventhubkafka-demo
data:
  sasl: "cGxhaW50ZXh0"                    # base64 encoded value of "plaintext". Do not change
  username: "JENvbm5lY3Rpb25TdHJpbmc="    # base64 encoded value of "$ConnectionString". Do not change
  tls: "ZW5hYmxl"
  password: "<eventhub_namespace_conn_string_base64encoded>"
  kafka_bootstrapservers: "<eventhub_namespace_hostname_withKafkaport_baseencoded>"
  kafka_topic: "<eventhub_name_base64encoded>"